### DISCUSSION TITLE
Is there any way to highlight the Saturday and Sunday columns?

### DISCUSSION THREAD

**Discussion by ademaro** [vkurko/calendar#154] [Q&A]
Done so far, but it's not the best option, I suspect (my week starts on Monday). I would be grateful if you could tell me how to do it more correctly.

```css
.ec-month .ec-content .ec-day:nth-last-of-type(1),
.ec-month .ec-content .ec-day:nth-last-of-type(2),
.ec-week .ec-content .ec-day:nth-last-of-type(1),
.ec-week .ec-content .ec-day:nth-last-of-type(2) {
  background-color: #ececec;
}
```
