### ISSUE TITLE
how to increase time slot height in "resourceTimeGridDay" ?

### ISSUE THREAD

**Issue by heatlai** [vkurko/calendar#1]
default time slot height is too short, i want show full info.

**Comment by vkurko** [comment]
There is currently no way to change the height of the slots. But there is an easy way to show all event content on mouseover.

All it takes is just this CSS rule:

```css
.ec-event:hover {
  height: auto !important;
}
```

See an example [here](http://jsbin.com/gaditewosu/edit?css,output).
