### ISSUE TITLE
trigger eventMouseEnter on background events?

### ISSUE THREAD

**Issue by mrvnklm** [vkurko/calendar#105]
Is there a possibility to trigger `eventMouseEnter` or other events also on background events?

**Comment by vkurko** [comment]
Try adding `z-index: 1` to `ec-bg-event` class:

```css
.ec-bg-event {
    z-index: 1;
}
```

I think I should include this in the next release.
