### ISSUE TITLE
Add some of the global.css styles to the core css

### ISSUE THREAD

**Issue by jt196** [vkurko/calendar#240]
Great job on the calendar! It's working pretty well, but I had to add the styles from the [global.css](https://github.com/vkurko/calendar/blob/master/docs/global.css) file to some global css on my Svelte site to get the month to display correctly (consistent line height) as well as the page height down to a sensible level. 

It would be nice if these defaults were included in the core css.

**Comment by vkurko** [comment]
What exact styles did you have to add from global.css?

**Comment by jt196** [comment]
Hey dude thanks for the quick response - all the height ones for the grid etc. 

Without this one:

```CSS
@media (min-width: 1200px) {
	.ec.ec-day-grid {
		height: 800px;
	}
}
```
It displays like this:

![image](https://github.com/vkurko/calendar/assets/8290163/1d8cbd8e-0a2b-4a20-b650-3ed48deaddf3)

The others help to set a height to the calendar and make it scrollable. 

```CSS
.ec {
	height: 640px;
}
.ec.ec-day-grid {
	height: 400px;
}
@media (min-width: 576px) {
	.ec {
		height: 700px;
	}
	.ec.ec-day-grid {
		height: 500px;
	}
}
@media (min-width: 992px) {
	.ec {
		height: 800px;
	}
	.ec.ec-day-grid {
		height: 700px;
	}
}
```
