### ISSUE TITLE
Fill width for resourceTimeline view

### ISSUE THREAD

**Issue by LMarcinkowski** [vkurko/calendar#385]
![Zrzut ekranu 2024-11-25 o 22 35 09](https://github.com/user-attachments/assets/b97e6a59-e277-46b7-bc5b-d68452992034)

Is it possible to make this view responsive?

**Comment by vkurko** [comment]
For `resourceTimelineMonth` only:

```css
.ec-timeline.ec-resource-month-view .ec-time, .ec-timeline.ec-resource-month-view .ec-line {
    width: 150px;
    flex-grow: 1;
}
.ec-timeline.ec-resource-month-view .ec-main {
    flex-grow: 1;
}
.ec-timeline.ec-resource-month-view .ec-header .ec-day {
    flex-direction: row;
}
```

You can notice that in this case the 150px value works as a minimum column width.
