### ISSUE TITLE
Turn off the display of the days

### ISSUE THREAD

**Issue by Akiyama-Shoichi** [vkurko/calendar#82]
Hello,
first many thanks for this awesome project.

Here is my issue :
The day of the week display in the header must be hidden in the time grid view.
Can I turn off the display of the days of the week in the header?

**Comment by vkurko** [comment]
There is no setting for this but you can hide it with CSS. Something like this:

```css
.ec-header {
  display: none;
}
.ec-all-day {
  border-top: 1px solid #dadce0;
}
```

Will this work for you?
